Fix flaky `test_sync_waiter_timeout_in_worker_thread` test
This test flaked by having the time comparison be milliseconds over the
1 second window imposed in the test. This PR bumps that to a two second
window to account for these small variations.

```
__________________ test_sync_waiter_timeout_in_worker_thread ___________________
[gw2] linux -- Python 3.10.14 /opt/hostedtoolcache/Python/3.10.14/x64/bin/python3

    def test_sync_waiter_timeout_in_worker_thread():
        """
        In this test, a timeout is raised due to a slow call that is occurring on the worker
        thread.
        """
        done_callback = Call.new(identity, 1)

        with WorkerThread(run_once=True) as runner:
            call = Call.new(sleep_repeatedly, 1)
            waiter = SyncWaiter(call)
            waiter.add_done_callback(done_callback)
            call.set_timeout(0.1)
            runner.submit(call)

        t0 = time.time()
        waiter.wait()
        t1 = time.time()

        with pytest.raises(CancelledError):
            call.result()

>       assert t1 - t0 < 1
E       assert (1717602059.3252807 - 1717602058.1010525) < 1

tests/_internal/concurrency/test_waiters.py:129: AssertionError
```