feat: support parsing TOML 1.0 on Python 3.11+
It fixes parsing pyproject.toml that contains:

```toml
[dependency-groups]
dev = [
    "dummy-dependency~=1.2.0",
    {include-group = "dummy-group-name"},
]
```

See https://peps.python.org/pep-0735/#dependency-group-include

Before the patch (toml), there is IndexError:

```shell
prefect --help
Failed to initialize plugins: list index out of range
Traceback (most recent call last):
  File "/.venv/bin/prefect", line 4, in <module>
    from prefect.cli import app
  File "/.venv/lib/python3.11/site-packages/prefect/cli/__init__.py", line 2, in <module>
    from prefect.cli.root import app
  File "/.venv/lib/python3.11/site-packages/prefect/cli/root.py", line 15, in <module>
    import prefect.context
  File "/.venv/lib/python3.11/site-packages/prefect/context.py", line 990, in <module>
    GLOBAL_SETTINGS_CONTEXT: SettingsContext = root_settings_context()
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/context.py", line 949, in root_settings_context
    profiles = prefect.settings.load_profiles()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/settings/profiles.py", line 307, in load_profiles
    current_settings = get_current_settings()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/settings/context.py", line 21, in get_current_settings
    return Settings()
           ^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 195, in __init__
    **__pydantic_self__._settings_build_values(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 391, in _settings_build_values
    sources = self.settings_customise_sources(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/settings/base.py", line 87, in settings_customise_sources    PyprojectTomlConfigSettingsSource(settings_cls),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/settings/sources.py", line 302, in __init__
    self.toml_data: dict[str, Any] = self._read_files(self.toml_file_path)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/pydantic_settings/sources/base.py", line 204, in _read_files
    vars.update(self._read_file(file_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/settings/sources.py", line 233, in _read_file
    return _read_toml_file(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/prefect/settings/sources.py", line 36, in _read_toml_file
    data = toml.load(path)  # type: ignore
           ^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
            ^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 1002, in load_array
    a[b] = a[b] + ',' + a[b + 1]
                        ~^^^^^^^
IndexError: list index out of range
```

that boils down to:

```shell
$ python -c 'import sys, toml; print(toml.load(sys.stdin))' < pyproject.toml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
            ^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/toml/decoder.py", line 1002, in load_array
    a[b] = a[b] + ',' + a[b + 1]
                        ~^^^^^^^
IndexError: list index out of range
```

With the patch (tomllib on Python 3.11+), no error:

```
$ python -c 'import sys, tomllib; print(tomllib.load(sys.stdin.buffer))' < pyproject.toml
{'dependency-groups': {'dev': ['dummy-dependency~=1.2.0', {'include-group': 'dummy-group-name'}]}}
```

No change in behavior on Python <3.11

No change in behavior for toml files that were previously
understood (valid according to the `toml` lib) even on Python 3.11+.
Some files (such in the example above) are accepted now that were
rejected previously.