Update global-concurrency-limits.mdx - Remove `await` for task submissions
Awaiting task submissions in the async code examples throws an error with Prefect 3.0. ie:

TypeError: object PrefectConcurrentFuture can't be used in 'await' expression

Updating the examples so that `await` is no longer included before submitting a task allows them to complete successfully.